name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Production
      - dev   # Staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_SSH_PRIVATE_KEY || secrets.STAGING_SSH_PRIVATE_KEY }}

      - name: Copy Files to Azure VM
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            scp -o StrictHostKeyChecking=no -r production/* user@${{ secrets.PRODUCTION_VM_IP }}:/var/www/html/
          else
            scp -o StrictHostKeyChecking=no -r staging/* user@${{ secrets.STAGING_VM_IP }}:/var/www/html/
          fi

      - name: Restart Apache Service
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            ssh -o StrictHostKeyChecking=no user@${{ secrets.PRODUCTION_VM_IP }} "sudo systemctl restart apache2"
          else
            ssh -o StrictHostKeyChecking=no user@${{ secrets.STAGING_VM_IP }} "sudo systemctl restart apache2"
          fi




